name: Terraform CI/CD Pipeline (Auto)

on:
  workflow_dispatch:
    inputs:
      tf_env:
        description: 'Target environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      tf_action:
        description: 'Action to perform'
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - promote
          - destroy

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.6.6
  TF_IN_AUTOMATION: true
  TF_DIR: ./terra

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: AWS OIDC Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PYFLEET_ARN }}-${{ github.event.inputs.tf_env }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Ensure Terraform Backend Exists
        if: ${{ github.event.inputs.tf_action != 'destroy-backend' }}
        run: |
          BUCKET_NAME="pyfleet-backend-tf"
          LOCK_TABLE="pyfleet-lock-tf"

          # Check S3 bucket
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "✅ S3 bucket $BUCKET_NAME already exists"
          else
            echo "⚠️ S3 bucket $BUCKET_NAME not found. Creating..."
            if [ "$AWS_REGION" = "us-east-1" ]; then
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME"
                --region "$AWS_REGION"
            else
              echo "Detected Region: ${AWS_REGION}. Using LocationConstraint"
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME" \
                --region "$AWS_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
            echo "✅ S3 bucket $BUCKET_NAME created"
          fi

          # Check DynamoDB table
          if aws dynamodb describe-table --table-name "$LOCK_TABLE" 2>/dev/null; then
            echo "✅ DynamoDB table $LOCK_TABLE already exists"
          else
            echo "⚠️ DynamoDB table $LOCK_TABLE not found. Creating..."
            aws dynamodb create-table \
              --table-name "$LOCK_TABLE" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
            echo "✅ DynamoDB table $LOCK_TABLE created"
          fi
        shell: bash


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Format Check
        run: |
            terraform fmt -check -recursive || { echo "Run 'terraform fmt -recursive' locally fix formatting"; exit 1; }
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      # -------------------------
      # Security Scan (tfsec)
      # -------------------------
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.TF_DIR }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------
      # Infracost Setup & Scan
      # -------------------------
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost Breakdown
        run: infracost breakdown --path ${{ env.TF_DIR }} --format json --out-file infracost.json

      - name: Infracost Diff
        run: infracost diff --path ${{ env.TF_DIR }} --compare-to infracost.json

      # -------------------------
      # Determine Active Color (Prod only)
      # -------------------------
      - name: Determine Active Color (Prod)
        if: ${{ github.event.inputs.tf_env == 'prod' && github.event.inputs.tf_action == 'promote' }}
        id: active_asg
        run: |
          CURRENT=$(terraform output -raw active_asg)
          echo "current=$CURRENT" >> $GITHUB_ENV
          if [[ "$CURRENT" == "asg_blue" ]]; then
            echo "next_color=green" >> $GITHUB_ENV
          else
            echo "next_color=blue" >> $GITHUB_ENV
          fi
          echo "Promoting to ${{ env.next_color }}"
        working-directory: ${{ env.TF_DIR }}

      # -------------------------
      # Terraform Plan
      # -------------------------
      - name: Terraform Plan
        if: ${{ github.event.inputs.tf_action == 'plan' || github.event.inputs.tf_action == 'promote' }}
        run: |
          if [[ "${{ github.event.inputs.tf_action }}" == "promote" ]]; then
            terraform plan -var="active_color=${{ env.next_color }}"
          else
            terraform plan -var="active_color=blue"
        working-directory: ${{ env.TF_DIR }}

      # -------------------------
      # Terraform Apply
      # -------------------------
      - name: Terraform Apply
        if: ${{ github.event.inputs.tf_action == 'apply' || github.event.inputs.tf_action == 'promote' }}
        run: |
          if [[ "${{ github.event.inputs.tf_action }}" == "promote" ]]; then
            terraform apply -auto-approve -var="active_color=${{ env.next_color }}"
          else
            terraform apply -auto-approve -var="active_color=blue"
        working-directory: ${{ env.TF_DIR }}

      # -------------------------
      # Terraform Destroy
      # -------------------------
      - name: Terraform Destroy
        if: ${{ github.event.inputs.tf_action == 'destroy' }}
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_DIR }}


      - name: Destroy S3 Backend and Lock Table Too
        run: |
          BUCKET_NAME="pyfleet-backend-tf"
          LOCK_TABLE="pyfleet-lock-tf"

          echo "Deleting Terraform backend S3 bucket and DynamoDB table..."

          # Delete DynamoDB table
          aws dynamodb delete-table --table-name "$LOCK_TABLE" || echo "DynamoDB table $LOCK_TABLE does not exist"

          # Empty and delete S3 bucket
          aws s3 rm s3://"$BUCKET_NAME" --recursive || echo "S3 bucket $BUCKET_NAME is empty or does not exist"
          aws s3api delete-bucket --bucket "$BUCKET_NAME" || echo "S3 bucket $BUCKET_NAME does not exist"

          echo "✅ Terraform backend destroyed"

          # -------------------------
          # Confirm backend deletion
          # -------------------------

          # Check DynamoDB table
          if ! aws dynamodb describe-table --table-name "$LOCK_TABLE" --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "✅ DynamoDB table $LOCK_TABLE confirmed deleted"
          else
            echo "❌ DynamoDB table $LOCK_TABLE still exists"
          fi

          # Check S3 bucket
          if ! aws s3 ls "s3://$BUCKET_NAME" >/dev/null 2>&1; then
            echo "✅ S3 bucket $BUCKET_NAME confirmed deleted"
          else
            echo "❌ S3 bucket $BUCKET_NAME still exists or not empty"
          fi

        shell: bash
